class Category < ApplicationRecord
  # Assoications
  belongs_to :parent, class_name: 'Category', optional: true
  has_many :subcategories, class_name: 'Category',
                           foreign_key: :parent_id,
                           dependent: :destroy,
                           inverse_of: :parent

  has_many :product_categories, dependent: :destroy
  has_many :products, through: :product_categories

  # Validations
  validates :name, presence: true, uniqueness: true
  validates :slug, presence: true,
                   uniqueness: { case_sensitive: false },
                   format: { with: /\A[a-z0-9-]+\z/ }

  # Scopes
  # lambda to prevent code to be loaded once (only when app start)
  scope :roots, -> { where(parent_id: nil).order(:position) }
  scope :ordered, -> { order(:position) }
  scope :by_depth, lambda { |depth|
    case depth
    when 0
      where(parent_id: nil)
    when 1
      where.not(parent_id: nil)
    else
      # to not break query chain and avoid nil exception in rails model (we need ActiveRecord::Relation in scope's always)
      all
    end
  }

  # Callbacks
  before_validation :generate_slug, if: :name_changed? # auto-generated by ApplicationRecord

  # Instance
  def root?
    parent_id.nil?
  end

  def depth
    parent ? parent.depth + 1 : 0
  end

  private

  def generate_slug
    self.slug = name.parameterize if name.present?
  end
end
